language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version
    - build-tools-27.0.3
    # The compile SDK version
    - android-27
    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
before_script: 
  - chmod +x gradlew